version: '3'
services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb-ssc/conf:/etc/influxdb
      - ./data/influxdb-ssc/db:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=ssc
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_DB=simplestatcollector
  grafana:
    restart: always
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana/prov:/etc/grafana/provisioning
    ports:
      - "30001:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb